### ISSUE TITLE
Generar base de 215 preguntas

### ISSUE THREAD

**Issue by roberto-reyes-stori** [Chatbots-Inc/test_bot#1]
Cada quien puede generar 100 y con eso empezamos.

Hoja de cálculo para agregar las preguntas. [Click aquí](https://docs.google.com/spreadsheets/d/1jOII-PHGW9gPnRnJHVo3Nd8MWyoL-pW6FRE-2BdvZ2E/edit?usp=sharing).

**Comment by roberto-reyes-stori** [comment]
@diegoajv, ¿puedes sugerir alguna técnica de datamining que conozcas para que esto no nos tome tanto tiempo?

**Comment by dajvisha** [comment]
@CR-Reyes creo que la otra sería dado un texto encontrar las entidades y las posibles intenciones que se podrían resolver con dicho extracto de texto. Eso en la situación de que lo que se quiere solucionar es encontrar una posible respuesta para una consulta que no aparece en la estructura que aloja las preguntas y respuestas. Al igual que en en el trabajo actual, tendriamos que iniciar con proceso manual.

**Comment by roberto-reyes-stori** [comment]
Me parece que sería conveniente iniciar con una especie de glosario (entidades) de inteligencia artificial y después identificarlas como dices en un texto para saber qué tanto podemos obtener de cada una.

**Comment by dajvisha** [comment]
@CR-Reyes relacionado a #3 hay un concepto llamado [Linked Data](http://linkeddata.org/) que consiste en generar relaciones entre datos, similar a la forma en que funciona la web. Entonces podemos generar un diccionario de entidades, como lo estas proponiendo, y utilizar un poco del concepto de "Linked Data", por ejemplo:

Entidades: [Inteligencia Artificial, etc...]
Intenciones: [Concepto, Ejemplo, Explicación formal, etc...]

Texto 1:
La inteligencia artificial es una rama de ....

Texto 2:
Un ejemplo practico de la inteligencia artificial es ...

Para el texto 1 podremos identificar la entidad "Inteligencia Artificial" y la intención "Definición". Para el texto 2 seria "Inteligencia Artificial" como entidad y "Ejemplo" como definición. Suponiendo que estas dos intenciones tienen una coeficiente de relación de 75%. Podríamos hacer lo siguiente:

Si el usuario pregunta: ¿Qué es la inteligencia artificial? y si dicha pregunta no se encuentra en la BD de respuestas, se podría utilizar este mini algoritmo para tratar de generar una respuesta. Dicha respuesta sería la concatenación de ambos textos.

En un caso esta respuesta sería enviada a un moderador para revisar que este correcta, de ser así se agregaría a la BD. 

En otras palabras, seguir un modelo de esta forma podría crear una arquitectura escalable. Volviendo al concepto de "Linked Data", podríamos fragmentar la información de la siguiente forma:
- Pregunta
- Intenciones
- Entidades
- Texto
- Recursos
Y crear relaciones entre ellas. Se podría agregar lo que propuso Diego Solis, mostrar contenido relacionado, en ese caso el problema que yo veía es que se podrían llegar a mostrar preguntas que estaban muy fuera del contexto actual. Entonces, se utilizaria una variable global para llevar un seguimiento del contexto, y creo que para este caso el contexto estaría delimitado por el tema actual. Entonces se agregaría Tema en la lista anterior. 

Esa es una idea mas o menos de lo que se podría lograr. Las tareas a desarrollar si irían definiendo a los alcances marcados. 

Nota: Funcionaria mejor explicándolo con un diagrama.

**Comment by diegoajv** [comment]
Prueba

**Comment by roberto-reyes-stori** [comment]
Me late esa estructura @diegoajv, ya había pensado previamente en el tema del contexto. De hecho, tenía la duda de si guardarlo en la base de datos, o guardarlo a través de Dialogflow, y después recuperarlo en cada input del usuario.

La idea era comenzar con un string vacío y en cuanto se mencionara algún concepto, tomarlo como contexto y no soltarlo hasta que se mencionara otro concepto diferente.

**Comment by roberto-reyes-stori** [comment]
Se terminaron por generar 215 preguntas 103 de ellas con respuesta. A la espera de más recursos para incrementar este número, esto posterior a un primer análisis de las preguntas que ya se tienen.
